repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [ "--fix" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - numpy>=1.24
          - pandas
          - torch
          - opencv-python-headless>=4.8
          - mediapipe>=0.10.14
          - scikit-learn>=1.3
          - tqdm
          - types-tqdm
          - PyQt6-stubs
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [ "-ll", "-r", "app/" ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
